"use client";

import { CssBaseline, ThemeProvider } from "@mui/material";
import "./globals.css";
import { lightTheme } from "./theme/themes";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <body id="__next">{children}</body>
      </ThemeProvider>
    </html>
  );
}
